# Configuration Jekyll pour GitHub Pages
title: "Louis Subtil | Portfolio"
description: "Portfolio de Louis Subtil - Étudiant en Informatique à l'Université du Mans"
author: "Louis Subtil"
email: "louis.subtil@etu.univ-lemans.fr"
url: "https://louno172.github.io"
baseurl: ""

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
theme: minima
encoding: utf-8

# Plugins essentiels uniquement
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Configuration des assets
sass:
  style: compressed
  sourcemap: never

# Configuration du site
timezone: Europe/Paris
locale: fr_FR

# Variables personnalisées
github_username: louno172
university: "Université du Mans"
course: "Informatique"
location: "Le Mans, France"

# Réseaux sociaux
social:
  github: louno172
  email: louis.subtil@etu.univ-lemans.fr

# Navigation
navigation:
  - title: "Accueil"
    url: "/"
  - title: "À propos"
    url: "/#about"
  - title: "Portfolio"
    url: "/#portfolio"
  - title: "Contact"
    url: "/contact/"