# Configuration Jekyll pour le portfolio de Louis Subtil
title: "Louis Subtil | Portfolio"
description: "Portfolio de Louis Subtil - Étudiant en Informatique à l'Université du Mans"
author: "Louis Subtil"
email: "louis.subtil@etu.univ-lemans.fr"
url: "https://louno172.github.io"
baseurl: "/Louno172"

# Configuration Jekyll
markdown: kramdown
highlighter: rouge
theme: minima
encoding: utf-8

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-sass-converter
  - jekyll-relative-links

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  blog:
    output: true
    permalink: /blog/:year/:month/:day/:title/

# Configuration des pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "blog"
    values:
      layout: "post"

# Configuration des assets
sass:
  style: compressed
  sourcemap: never

# Configuration du site
timezone: Europe/Paris
locale: fr_FR

# Variables personnalisées
github_username: louno172
university: "Université du Mans"
course: "Informatique"
location: "Le Mans, France"

# Réseaux sociaux
social:
  github: louno172
  linkedin: louis-subtil
  email: louis.subtil@etu.univ-lemans.fr

# Navigation
navigation:
  - title: "Accueil"
    url: "/"
  - title: "À propos"
    url: "/#about"
  - title: "Portfolio"
    url: "/#portfolio"
  - title: "Contact"
    url: "/contact/"

# Configuration SEO
seo:
  type: "Person"
  image: "/assets/images/og-image.jpg"
  twitter:
    creator: "@louno172"
    site: "@louno172"
